@startuml state-diagram
[*] --> Инициация

Инициация --> Регистрация : Создать мероприятие
Регистрация --> Отбор : Провести регистрацию
Отбор --> В_процессе : Допустить команды
В_процессе : Выдать кейс
В_процессе : Провести чекпоинт
В_процессе : Выставить тех поражение
В_процессе : Открыть область загрузки
В_процессе --> Завершение_работы : Закрыть область загрузки
Завершение_работы --> Защита_и_итоги : Допустить до защиты
Защита_и_итоги : Назначить призеров
Защита_и_итоги : Выдать сертификаты и дипломы
Защита_и_итоги --> [*]

@enduml
