@startwbs
* Разработка системы онлайн-курсов
** Инициация проекта
*** Определение целей и задач платформы
*** Идентификация заинтересованных сторон
**** Организаторы
**** Администраторы
 ** Планирование
*** Разработка плана проекта
*** Оценка ресурсов
*** Определение рисков
 ** Анализ требований
*** Анализ бизнес-процессов
**** Процессы авторизации и регистрации
**** Процессы создания гемджемов
**** Процессы размещения задания
*** Анализ технических требований
**** Требования к производительности
**** Требования к безопасности
**** Требования к интеграции
 ** Проектирование системы
*** Архитектурное проектирование
**** Проектирование бизнес-уровня
**** Проектирование уровня приложений
**** Проектирование технологического уровня
*** Проектирование баз данных
**** БД организаторов
**** БД геймджемов
*** Проектирование интерфейсов
**** Интерфейс администратора
**** Интерфейс организатора
 ** Разработка
*** Фронтенд-разработка
**** Разработка модуля авторизации
**** Разработка модуля просмотра заданий
**** Разработка модуля отправки работ
**** Разработка модуля управления профилем
*** Бэкенд-разработка
**** Разработка сервиса аутентификации
**** Разработка сервиса управления соревнованиями
**** Разработка сервиса пользователей
**** Разработка сервиса уведомлений
 ** Тестирование
*** Модульное тестирование
**** Тестирование фронтенд-компонентов
**** Тестирование бэкенд-сервисов
*** Интеграционное тестирование
*** Системное тестирование
*** Приемочное тестирование
 ** Развертывание
*** Настройка веб-сервера
*** Настройка сервера приложений
*** Настройка баз данных
*** Настройка репликации БД
 ** Поддержка и сопровождение
*** Мониторинг производительности системы
*** Обработка обращений пользователей
*** Обновление функционала
*** Резервное копирование данных
@endwbs