@startuml
'!include styles.puml;

[*] --> Регистрация : Начало участия

Регистрация --> Отказ : Заявка отклонена
Регистрация --> Отбор : Заявка подтверждена

Отбор --> Отказ : Не прошёл отбор
Отбор --> Участие : Отбор пройден

Участие --> ТехПоражение : Нарушение правил
Участие --> ЗагрузкаРешения : Задача решена

ЗагрузкаРешения --> Участие : Ошибка загрузки
ЗагрузкаРешения --> Защита : Решение успешно загружено

Защита --> Награждение : Признан победителем
Защита --> Завершение : Участие завершено

Награждение --> [*] : Получение награды
Отказ --> [*] : Уведомление об отказе
ТехПоражение --> [*] : Дисквалификация
Завершение --> [*] : Подведение итогов
@enduml


Регистрация --> Отказ : Заявка отклонена
ЗагрузкаРешения --> Защита : Успешная загрузка
Защита --> Награждение : Победа
Защита --> Завершение : Участие завершено
@enduml

